spring:
  datasource:
    url: jdbc:oracle:thin:@172.21.20.88:1521:CVDBPWDE
    username: portalweb
    password: portalweb
  
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        
      